<?php

namespace myerm\shop\common\models;

use myerm\common\models\MyERMModel;

/**
 * ShopERM的Model类
 */
class ShopModel extends MyERMModel
{
    /*
     * 事件集合
     */
    public $events;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        //注册事件处理器，2017年9月13日 17:37:31，Mars
        if ($this->events) {
            foreach ($this->events as $e) {
                $this->on($e[0], $e[1]);
            }
        }
    }

    /**
     * 获得ShopERM的版本号
     * @time 2017年9月14日 15:46:48
     * @author
     * @return string
     */
    public function version()
    {
        return "1.0.0";
    }

    /**
     * 通过ID查找数据
     * @param $ID
     * @return static
     */
    public static function findByID($ID)
    {
        return static::findOne($ID);
    }

    /**
     * 通过ID数组查找N个数据
     * @param $arrID
     */
    public static function findByIDs($arrID)
    {
        return static::findAll(['lID'=>$arrID]);
    }
}