#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

error_reporting(E_ALL & ~E_NOTICE & ~E_STRICT & ~E_WARNING);
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');
defined('YII_CONSOLE') or define('YII_CONSOLE', true);

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/apps/shop/console/config/console.php');

Yii::setAlias('@myerm', __DIR__ . '/apps');
Yii::setAlias('@console', __DIR__ . '/apps/shop/console');

$application = new yii\console\Application($config);

Yii::$app->on('beforeRequest', function ($event) {
    $GLOBALS['dbTransaction'] = \Yii::$app->db->beginTransaction();
});

Yii::$app->on('afterRequest', function ($event) {
    $GLOBALS['dbTransaction']->commit();
});


$exitCode = $application->run();
exit($exitCode);
