<?php

namespace myerm\shop\common\components;

use myerm\shop\common\models\MallConfig;

/**
 *  微信类
 */
class Wechat extends \maxwen\easywechat\Wechat
{
    /**
     * 重载父类，为的是加载配置。
     */
    public function init()
    {
        //加载微信配置
        \Yii::$app->params['WECHAT']['app_id'] = MallConfig::getValueByKey("sAppID");
        \Yii::$app->params['WECHAT']['secret'] = MallConfig::getValueByKey("sAppSecret");
        \Yii::$app->params['WECHAT']['token'] = MallConfig::getValueByKey("sToken");
        \Yii::$app->params['WECHAT']['payment']['merchant_id'] = MallConfig::getValueByKey("sMerchantID");
        \Yii::$app->params['WECHAT']['payment']['cert_path'] = realpath(\Yii::getAlias("@myerm") . "/../resources/wxpay/apiclient_cert.pem");
        \Yii::$app->params['WECHAT']['payment']['key_path'] = realpath(\Yii::getAlias("@myerm") . "/../resources/wxpay/apiclient_key.pem");
        \Yii::$app->params['WECHAT']['payment']['key'] = MallConfig::getValueByKey("sWXPayKey");


        parent::init(); // TODO: Change the autogenerated stub
    }
}