###服务端口号
server:
  port: 8888
##定义服务名称
spring:
  application:
    name: eureka-server
eureka:
  instance:
    ###注册中心ip地址
    hostname: 127.0.0.1
  client:
    serviceUrl:
      ##注册地址
      defaultZone: http://${eureka.instance.hostname}:8888/eureka/
    ####因为自己是注册中心，是否需要将自己注册给自己的注册中心（集群的时候是需要是为true）
    register-with-eureka: false
    ###因为自己是注册中心， 不需要去检索服务信息
    fetch-registry: false
  server:
    # 测试时关闭自我保护机制，保证不可用服务及时踢出,,,若要及时踢出过期服务,还需要在客户端进行配置
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
  security:
    username: root
    password: 123456