<?php

namespace myerm\common\models;

use yii;
use yii\base\Application;

class Debug extends \yii\debug\Module
{
    /**
     * 默认视图路径
     */
    public $defaultViewPath = '@yii/debug/views';


    public function bootstrap($app)
    {
        $this->setDataPath();

        //配置视图路径
        $this->setViewPath($this->defaultViewPath);

        parent::bootstrap($app); // TODO: Change the autogenerated stub

        $app->getUrlManager()->addRules([
            [
                'class' => 'yii\web\UrlRule',
                'route' => $this->id . '/default/<action>',
                'pattern' => $this->id . '/<controller:[\w\-]+>/<action:[\w\-]+>',
            ]
        ], false);

        //拦截输出，将默认的详情视图路径替换为当前视图路径
        $app->on(Application::EVENT_AFTER_REQUEST, function () use ($app) {
            $pathInfo = \Yii::$app->request->pathInfo;
            $arrPart = explode("/", $pathInfo);
            $app->response->data = str_replace('debug/default/view', 'debug/' . $arrPart[1] . "/view", $app->response->data);
            $app->response->data = str_replace('debug/default/index', 'debug/' . $arrPart[1] . "/index", $app->response->data);
        });
    }

    public function setDataPath()
    {
        $pathInfo = Yii::$app->request->pathInfo;
        $arrPart = explode("/", $pathInfo);

        if ($arrPart[0] == 'debug') {
            $this->dataPath = Yii::getAlias('@runtime/debug/'.$arrPart[1]);
        } else {
            $this->dataPath = Yii::getAlias('@runtime/debug/'.$arrPart[0]);
        }
    }
}