<?php

namespace myerm\shop\common\models\debug;

use yii;
use yii\base\Application;

/**
 * 重构了Debug类，按控制器来分类。
 * ============================================================================
 * 版权所有 2010-2017 三只象（厦门）网络科技有限公司，并保留所有权利。
 * 网站地址: http://www.myerm.cn
 * ----------------------------------------------------------------------------
 * 这不是一个自由软件！您只能在不用于商业目的的前提下对程序代码进行修改和
 * 使用；不允许对程序代码以任何形式任何目的的再发布。
 * ============================================================================
 * @author 陈鹭明  <lumingchen@qq.com>
 * @since 2017年9月4日 22:22:57
 * @version v2.0
 */
class Module extends \yii\debug\Module
{
    public function bootstrap($app)
    {
        $this->historySize = 1000000;

        //配置视图路径
        $this->setViewPath('@yii/debug/views');

        if (Yii::$app->request->pathInfo == 'debug/default/view') {
            $debug = ShopDebug::findOne($_GET['tag']);
            $this->dataPath = dirname($debug->sSavePath);
        } else {
            //debug数据按日期来存放
            $this->dataPath = Yii::getAlias("@myerm/common/runtime/debug/".\Yii::$app->formatter->asDate(time()));
        }

        parent::bootstrap($app); // TODO: Change the autogenerated stub

        $this->logTarget = Yii::$app->getLog()->targets['debug'] = new LogTarget($this);
    }
}