<?php

namespace myerm\shop\backend\controllers;

use myerm\backend\common\controllers\ObjectController;
use myerm\backend\common\libs\File;
use myerm\backend\common\libs\NewID;
use myerm\backend\system\models\SysUI;
use myerm\common\components\Image;
use myerm\common\components\simple_html_dom;
use myerm\shop\backend\models\ProductModifyLog;
use myerm\shop\backend\models\ProductSKU;
use myerm\shop\backend\models\ProductSpecification;
use myerm\shop\common\models\Import;
use myerm\shop\common\models\PreOrder;
use myerm\shop\common\models\Product;
use yii\base\UserException;

/**
 * 产品
 */
class ImportController extends BackendController
{
    public function getHomeTabs()
    {
        $data = [];
        $data['arrList'] = [];

        $list = [];
        $list['ID'] = '0';
        $list['sName'] = '导入成功';
        $list['sKey'] = 'Main.Shop.Import.List.All';
        $list['sLinkUrl'] = \Yii::$app->homeUrl . '/' . strtolower($this->sObjectName) . '/getlisttable?sListKey=Main.Shop.Import.List.All&sTabID=success&sExtra=success';
        $data['arrList'][] = $list;

        $list['ID'] = '1';
        $list['sName'] = '导入失败';
        $list['sKey'] = 'Main.Shop.Import.List.All';
        $list['sLinkUrl'] = \Yii::$app->homeUrl . '/' . strtolower($this->sObjectName) . '/getlisttable?sListKey=Main.Shop.Import.List.All&sTabID=error&sExtra=error';
        $data['arrList'][] = $list;

        $list['ID'] = '2';
        $list['sName'] = '已提交';
        $list['sKey'] = 'Main.Shop.Import.List.All';
        $list['sLinkUrl'] = \Yii::$app->homeUrl . '/' . strtolower($this->sObjectName) . '/getlisttable?sListKey=Main.Shop.Import.List.All&sTabID=submit&sExtra=submit';
        $data['arrList'][] = $list;

        return $this->renderPartial('@app/common/views/hometabs', $data);
    }

    public function listDataConfig($sysList, $arrConfig)
    {
        $arrConfig['arrFlt'][] = [
            'sField' => 'buyerID',
            'sOper' => 'equal',
            'sValue' => $this->BuyerID,
            'sSQL' => "buyerID='" . $this->BuyerID . "'"
        ];

        if ($_POST['sExtra'] == 'all') {

        } elseif ($_POST['sExtra'] == 'success') {
            $arrConfig['arrFlt'][] = ['sField' => 'status', 'sOper' => 'equal', 'sValue' => '1'];
        } elseif ($_POST['sExtra'] == 'error') {
            $arrConfig['arrFlt'][] = ['sField' => 'status', 'sOper' => 'equal', 'sValue' => '0'];
        } elseif ($_POST['sExtra'] == 'submit') {
            $arrConfig['arrFlt'][] = ['sField' => 'status', 'sOper' => 'equal', 'sValue' => '2'];
        }
        return parent::listDataConfig($sysList, $arrConfig);
    }

    public function afterEditSave()
    {
        $arr = $_POST['arrObjectData']['Shop/Import'];
        $data = PreOrder::checkImportRecord($arr);
        $import = Import::findOne($_POST['ID']);
        $import->cloudProductName = $data['cloudProductName'];
        $import->ShipTemplateID = $data['ShipTemplateID'];
        $import->sStandard = $data['sStandard'];//规格
        $import->sTaste = $data['sTaste'];//口味
        $import->sRemark = $data['sRemark'];
        $import->status = $data['status'];
        $import->bGroupProdcut = $data['bGroupProdcut'];
        $import->lGroupNum = $data['lGroupNum'];
        //收获地址
        $import->sAddressFinal = $data['sAddressFinal'];
        $import->ProvinceID = $data['ProvinceID'];
        $import->CityID = $data['CityID'];
        $import->AreaID = $data['AreaID'];
        $import->fPrice = $data['fPrice'];
        $import->save();
        //同名数据批量验证
        $arrImport = Import::find()->where(['orderName' => $import->orderName])->all();
        $key = $import->orderName . $import->sName . $import->sMobile . $import->ProvinceID . $import->CityID . $import->AreaID . $import->sAddressFinal;
        foreach ($arrImport as $import) {
            $newKey = $import->orderName . $import->sName . $import->sMobile . $import->ProvinceID . $import->CityID . $import->AreaID . $import->sAddressFinal;
            if ($newKey != $key) {
                $import->status = 0;
                $import->sRemark = $import->sRemark . '同一订单编号收货人信息不一致';
                $import->save();
            }
        }
        return parent::afterEditSave(); // TODO: Change the autogenerated stub
    }

    public function getListButton()
    {
        $data = [];
        return $this->renderPartial('listbutton', $data);
    }

    public function actionSavepreorder()
    {
        $sSelectedID = $_REQUEST['sSelectedID'];
        $res=PreOrder::savePrepOrder($sSelectedID, $this->BuyerID);
        if($res) {
            $sRespone = json_encode(['bSuccess' => true, 'sMsg' => '提交成功，请刷新数据']);
        }
        else{
            $sRespone = json_encode(['bSuccess' => false, 'sMsg' => '部分数据出错，请查看失败说明']);
        }
        return "var ret = " . $sRespone;
    }
}


