<?php

namespace myerm\shop\backend\controllers;

use myerm\backend\common\controllers\ObjectController;
use myerm\backend\common\libs\File;
use myerm\backend\common\libs\NewID;
use myerm\shop\backend\models\MallHomeProductConfig;


/**
 * 商城首页产品
 * ============================================================================
 * 版权所有 2010-2017 三只象（厦门）网络科技有限公司，并保留所有权利。
 * 网站地址: http://www.myerm.cn
 * ----------------------------------------------------------------------------
 * 这不是一个自由软件！您只能在不用于商业目的的前提下对程序代码进行修改和
 * 使用；不允许对程序代码以任何形式任何目的的再发布。
 * ============================================================================
 * @author 陈鹭明  <lumingchen@qq.com>
 * @since 2017年10月4日 13:25:32
 * @version v1.0
 */
class MallhomeproductconfigController extends ObjectController
{
    public function getNewFooterAppend()
    {
        $data = [];

        if ($_GET['ID']) {
            $config = MallHomeProductConfig::findByID($_GET['ID']);
            $data['arrDetail'] = $config->productDetail;
        }

        return $this->renderPartial('newfooter', $data);
    }

    public function getViewFooterAppend()
    {
        $config = MallHomeProductConfig::findByID($_GET['ID']);
        return $this->renderPartial('viewfooter', ['arrDetail'=>$config->productDetail]);
    }

    public function afterDel($arrData)
    {
        MallHomeProductConfig::updateCache();
        return parent::afterDel($arrData); // TODO: Change the autogenerated stub
    }

    public function beforeObjectNewSave($sysObject, $arrObjectData)
    {
        if ($_POST['arrObjectData']['Shop/MallHomeProductConfig']['sPicBase64']) {
            $arrFileInfo = File::parseImageFromBase64($_POST['arrObjectData']['Shop/MallHomeProductConfig']['sPicBase64']);
            $sFileName = NewID::make() . ".jpg";
            $arrObjectData['sPic'] = "ttt";
            $arrObjectData['sPicPath'] = File::putContentToUploadDir($sFileName, $arrFileInfo[1]);
        }

        $arrProductDetail = [];

        asort($_POST['arrObjectData']['Shop/MallHomeProductConfig']['lDetailPos']);
        foreach ($_POST['arrObjectData']['Shop/MallHomeProductConfig']['lDetailPos'] as $i => $lPos) {
            if ($_POST['arrObjectData']['Shop/MallHomeProductConfig']['sProductDetail'][$i]) {
                $arrProductDetail[] = [
                    'ProductID' => $_POST['arrObjectData']['Shop/MallHomeProductConfig']['sProductDetail'][$i],
                    'lPos' => $lPos,
                    'sPic' => $_POST['arrObjectData']['Shop/MallHomeProductConfig']['sLogo'][$i],
                    'sPicPath' => $_POST['arrObjectData']['Shop/MallHomeProductConfig']['sLogoPath'][$i],
                ];
            }
        }

        $arrObjectData['sProductDetail'] = json_encode($arrProductDetail);

        return parent::beforeObjectNewSave($sysObject, $arrObjectData); // TODO: Change the autogenerated stub
    }

    public function beforeObjectEditSave($sysObject, $ID, $arrObjectData)
    {
        if ($_POST['arrObjectData']['Shop/MallHomeProductConfig']['sPicBase64']) {
            $arrFileInfo = File::parseImageFromBase64($_POST['arrObjectData']['Shop/MallHomeProductConfig']['sPicBase64']);
            $sFileName = NewID::make() . ".".$arrFileInfo[0];
            $arrObjectData['sPic'] = "ttt";
            $arrObjectData['sPicPath'] = File::putContentToUploadDir($sFileName, $arrFileInfo[1]);
        }

        $arrProductDetail = [];

        asort($_POST['arrObjectData']['Shop/MallHomeProductConfig']['lDetailPos']);
        foreach ($_POST['arrObjectData']['Shop/MallHomeProductConfig']['lDetailPos'] as $i => $lPos) {
            if ($_POST['arrObjectData']['Shop/MallHomeProductConfig']['sProductDetail'][$i]) {
                $arrProductDetail[] = [
                    'ProductID' => $_POST['arrObjectData']['Shop/MallHomeProductConfig']['sProductDetail'][$i],
                    'lPos' => $lPos,
                    'sPic' => $_POST['arrObjectData']['Shop/MallHomeProductConfig']['sLogo'][$i],
                    'sPicPath' => $_POST['arrObjectData']['Shop/MallHomeProductConfig']['sLogoPath'][$i],
                ];
            }
        }

        $arrObjectData['sProductDetail'] = json_encode($arrProductDetail);

        return parent::beforeObjectEditSave($sysObject, $ID, $arrObjectData); // TODO: Change the autogenerated stub
    }

    public function afterObjectEditSave($sysObject, $ID)
    {
        MallHomeProductConfig::updateCache();
        return parent::afterObjectEditSave($sysObject, $ID); // TODO: Change the autogenerated stub
    }

    public function afterObjectNewSave($sysObject, $ID)
    {
        MallHomeProductConfig::updateCache();
        return parent::afterObjectNewSave($sysObject, $ID); // TODO: Change the autogenerated stub
    }
}