<?php

namespace myerm\shop\backend\controllers;


use myerm\backend\common\controllers\ObjectController;


/**
 * 订单付款记录
 * ============================================================================
 * 版权所有 2010-2017 三只象（厦门）网络科技有限公司，并保留所有权利。
 * 网站地址: http://www.myerm.cn
 * ----------------------------------------------------------------------------
 * 这不是一个自由软件！您只能在不用于商业目的的前提下对程序代码进行修改和
 * 使用；不允许对程序代码以任何形式任何目的的再发布。
 * ============================================================================
 * @author 陈鹭明  <lumingchen@qq.com>
 * @since 2017年11月15日 10:52:51
 * @version v1.0
 */
class OrderpaylogController extends ObjectController
{
    public function listDataConfig($sysList, $arrConfig)
    {
        foreach ($arrConfig['arrFlt'] as $i => $flt) {
            if ($flt['sField'] == 'sOrderNo') {
                $order = \Yii::$app->order->getByNo($flt['sValue']);
                $arrConfig['arrFlt'][] = ['sField' => 'sOrderID', 'sOper' => 'center', 'sValue' => $order->lID ? $order->lID : 1111];
            }
        }

        return parent::listDataConfig($sysList, $arrConfig); // TODO: Change the autogenerated stub
    }
}