<?php

namespace myerm\shop\backend\controllers;


use myerm\backend\common\controllers\ObjectController;
use myerm\backend\common\libs\File;
use myerm\backend\common\libs\NewID;
use myerm\shop\common\models\ProductTag;


/**
 * 标签
 * ============================================================================
 * 版权所有 2010-2017 三只象（厦门）网络科技有限公司，并保留所有权利。
 * 网站地址: http://www.myerm.cn
 * ----------------------------------------------------------------------------
 * 这不是一个自由软件！您只能在不用于商业目的的前提下对程序代码进行修改和
 * 使用；不允许对程序代码以任何形式任何目的的再发布。
 * ============================================================================
 * @author 陈鹭明  <lumingchen@qq.com>
 * @since 2017年9月25日 15:26:34
 * @version v1.0
 */
class ProducttagController extends ObjectController
{
    public function getNewFooterAppend()
    {
        $data = [];
        return $this->renderPartial('newfooter', $data);
    }

    public function beforeDel($arrData)
    {
        foreach ($arrData as $data) {
            if (ProductTag::findByID($data[$this->sysObject->sIDField])->lProductNum > 0) {
                throw new \yii\base\UserException('已有商品使用了该标签，不可删除。');
            }
        }
    }

    public function beforeObjectEditSave($sysObject, $ID, $arrObjectData)
    {
        if ($_POST['arrObjectData']['Shop/ProductTag']['sLogoBase64']) {
            if (substr($_POST['arrObjectData']['Shop/ProductTag']['sLogoBase64'], 0, 5) == 'data:') {
                $arrFileInfo = File::parseImageFromBase64($_POST['arrObjectData']['Shop/ProductTag']['sLogoBase64']);
                $sFileName = NewID::make() . "." . $arrFileInfo[0];;
                $arrObjectData['sLogoPath'] = File::putContentToUploadDir($sFileName, $arrFileInfo[1]);
            } else {
                $arrObjectData['sLogoPath'] = str_ireplace(\Yii::$app->params['sUploadUrl'] . "/", "",
                    $_POST['arrObjectData']['Shop/ProductTag']['sLogoBase64']);
            }
        }


        return parent::beforeObjectEditSave($sysObject, $ID, $arrObjectData); // TODO: Change the autogenerated stub
    }

    public function beforeObjectNewSave($sysObject, $arrObjectData)
    {
        if ($_POST['arrObjectData']['Shop/ProductTag']['sLogoBase64']) {
            if (substr($_POST['arrObjectData']['Shop/ProductTag']['sLogoBase64'], 0, 5) == 'data:') {
                $arrFileInfo = File::parseImageFromBase64($_POST['arrObjectData']['Shop/ProductTag']['sLogoBase64']);
                $sFileName = NewID::make() . "." . $arrFileInfo[0];;
                $arrObjectData['sLogoPath'] = File::putContentToUploadDir($sFileName, $arrFileInfo[1]);
            } else {
                $arrObjectData['sLogoPath'] = str_ireplace(\Yii::$app->params['sUploadUrl'] . "/", "",
                    $_POST['arrObjectData']['Shop/ProductTag']['sLogoBase64']);
            }
        }

        return parent::beforeObjectNewSave($sysObject, $arrObjectData); // TODO: Change the autogenerated stub
    }

    public function formatListData($arrData)
    {
        foreach ($arrData as $key => $data) {
            $arrData[$key]['sUrl'] = "<a href='" . \myerm\shop\common\models\MallConfig::getValueByKey('sMallRootUrl') . "/shop0/product/list?tag=".$data['lID']."' target='_blank'>/shop0/product/list?tag=".$data['lID']."</a>";
        }

        return $arrData;
    }

}