<?php

namespace myerm\shop\backend\controllers;

use myerm\backend\common\controllers\ObjectController;
use myerm\shop\common\models\ProductTag;


/**
 * 商品操作日志
 * ============================================================================
 * 版权所有 2010-2017 三只象（厦门）网络科技有限公司，并保留所有权利。
 * 网站地址: http://www.myerm.cn
 * ----------------------------------------------------------------------------
 * 这不是一个自由软件！您只能在不用于商业目的的前提下对程序代码进行修改和
 * 使用；不允许对程序代码以任何形式任何目的的再发布。
 * ============================================================================
 * @author 陈鹭明  <lumingchen@qq.com>
 * @since 2017年12月6日 09:38:30
 * @version v1.0
 */
class ProductmodifylogController extends ObjectController
{
    public function listDataConfig($sysList, $arrConfig)
    {
        foreach ($arrConfig['arrFlt'] as $k => $flt) {
            if ($flt['sField'] == 'sName') {
                $arrConfig['arrFlt'][] = ['sField'=>'ProductID','sOper'=>'center','sValue'=>$flt['sValue']];
                unset($arrConfig['arrFlt'][$k]);
            }
        }

        return parent::listDataConfig($sysList, $arrConfig); // TODO: Change the autogenerated stub
    }
}