<?php

namespace myerm\shop\backend\controllers;


use myerm\backend\common\controllers\ObjectController;


/**
 * 经销商类
 * ============================================================================
 * 版权所有 2010-2017 三只象（厦门）网络科技有限公司，并保留所有权利。
 * 网站地址: http://www.myerm.cn
 * ----------------------------------------------------------------------------
 * 这不是一个自由软件！您只能在不用于商业目的的前提下对程序代码进行修改和
 * 使用；不允许对程序代码以任何形式任何目的的再发布。
 * ============================================================================
 * @author 陈鹭明  <lumingchen@qq.com>
 * @since 2017年12月12日 11:11:28
 * @version v1.0
 */
class SellerController extends ObjectController
{
    public function beforeObjectEditSave($sysObject, $ID, $arrObjectData)
    {
        $seller = \Yii::$app->seller->findByID($ID);
        if (isset($arrObjectData['UpID']) && $seller->UpID != $arrObjectData['UpID']) {
            if ($arrObjectData['UpID']) {
                $upSeller = \Yii::$app->seller->findByID($arrObjectData['UpID']);
                $arrObjectData['UpUpID'] = $upSeller->UpID;
                $arrObjectData['PathID'] = $upSeller->PathID . $ID . "/";
            } else {
                $arrObjectData['UpUpID'] = null;
                $arrObjectData['UpID'] = null;
                $arrObjectData['PathID'] = "/$ID/";
            }

            $this->updatePathID($ID, $arrObjectData['UpID'], $arrObjectData['PathID']);
        }


        return parent::beforeObjectEditSave($sysObject, $ID, $arrObjectData); // TODO: Change the autogenerated stub
    }

    /**
     * 更新所有下级的PathID
     * @param $UpID
     * @param $PathID
     */
    public function updatePathID($UpID, $UpUpID, $PathID)
    {
        $allSubSeller = \Yii::$app->seller->findSub($UpID);
        foreach ($allSubSeller as $seller) {
            $seller->PathID = $PathID . $seller->lID . "/";
            $seller->UpUpID = $UpUpID;
            $seller->save();

            $this->updatePathID($seller->lID, $UpID, $seller->PathID);
        }
    }


    public function formatListData($arrData)
    {

        foreach ($arrData as $key => $data) {
            $data['fWithdraw'] = "<a href=\"javascript:;\" onclick=\"parent.addTab('" . $data['sName'] . "可提现明细', '/shop/sellerflow/home?SellerID=" . urlencode($data['sName']) . "')\">" . number_format($data['fWithdraw'],
                    2) . "</a>";

            $data['fUnsettlement'] = "<a href=\"javascript:;\" onclick=\"parent.addTab('" . $data['sName'] . "未结算订单', '/shop/order/home?StatusID=paid,delivered&SellerCommission=" . urlencode($data['sName']) . "')\">" . number_format($data['fUnsettlement'],
                    2) . "</a>";

            $data['fSettlement'] = "<a href=\"javascript:;\" onclick=\"parent.addTab('" . $data['sName'] . "已结算订单', '/shop/order/home?StatusID=success&SellerCommission=" . urlencode($data['sName']) . "')\">" . number_format($data['fSettlement'],
                    2) . "</a>";

            $data['fWithdrawed'] = "<a href=\"javascript:;\" onclick=\"parent.addTab('" . $data['sName'] . "提现记录', '/shop/sellerwithdrawlog/home?TypeID=1&SellerID=" . urlencode($data['sName']) . "')\">" . number_format($data['fWithdrawed'],
                    2) . "</a>";

            $data['fSumIncome'] = "<a href=\"javascript:;\" onclick=\"parent.addTab('" . $data['sName'] . "收入明细', '/shop/sellerflow/home?TypeID=1&SellerID=" . urlencode($data['sName']) . "')\">" . number_format($data['fSumIncome'],
                    2) . "</a>";

            $arrData[$key] = $data;
        }

        return parent::formatListData($arrData); // TODO: Change the autogenerated stub
    }

}