<?php

namespace myerm\shop\backend\controllers;

use myerm\backend\common\controllers\ObjectController;


/**
 * 经销商店铺
 * ============================================================================
 * 版权所有 2010-2017 三只象（厦门）网络科技有限公司，并保留所有权利。
 * 网站地址: http://www.myerm.cn
 * ----------------------------------------------------------------------------
 * 这不是一个自由软件！您只能在不用于商业目的的前提下对程序代码进行修改和
 * 使用；不允许对程序代码以任何形式任何目的的再发布。
 * ============================================================================
 * @author 陈鹭明  <lumingchen@qq.com>
 * @since 2017年12月19日 09:39:50
 * @version v1.0
 */
class SellerwithdrawlogController extends ObjectController
{
    public function getListButton()
    {
        return $this->renderPartial("listbutton");
    }

    public function formatListData($arrData)
    {
        foreach ($arrData as $lKey => $data) {
            $arrData[$lKey]['fMoney'] = number_format($data['fMoney'], 2);
        }


        return parent::formatListData($arrData); // TODO: Change the autogenerated stub
    }

    public function actionConfirmsave()
    {
        $arrData = $this->listBatch();

        foreach ($arrData as $data) {
            $log = \Yii::$app->sellerwithdrawlog->findByID($data['lID']);
            $log->confirm();
        }

        return $this->asJson(['bSuccess' => true, 'sMsg' => '操作成功']);
    }

    public function getViewFooterAppend()
    {
        $log = \Yii::$app->sellerwithdrawlog->findByID($_GET['ID']);
        return $this->renderPartial("viewfooter", ['arrLog' => json_decode($log->sLog)]);
    }
}