spring:
  application:
    name: service-api
server:
  port: 15001
mybatis-plus:
  type-aliases-package: group.dny.api.entity   # 定义所有操作类的别名所在包
  mapper-locations: classpath:mapper/*.xml # 所有的mapper映射文件
  configuration:
    lazy-loading-enabled: true #打开延迟加载的开关
    aggressive-lazy-loading: false #将积极加载改为消息加载即按需加载
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://root:123456@127.0.0.1:10001/eureka/
logging:
  config: classpath:logback-pro.xml
  level:
    group.dny.api.mapper: debug
pic:
  url: http://image.dny.group
datasource:
  url: jdbc:mysql://192.168.1.81:8635/dnycloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: dnyclouduser
  password: mhgkVzGC7r@#iNjD







