<?php

namespace myerm\backend\common\models\debug;

use yii;
use yii\base\Application;

/**
 * 重构了Debug类，按控制器来分类。
 */
class Module extends \yii\debug\Module
{
    public function bootstrap($app)
    {
        $this->historySize = 10000;

        //配置视图路径
        $this->setViewPath('@yii/debug/views');

        if (Yii::$app->request->pathInfo == 'debug/default/view') {
            $debug = SysDebug::findOne($_GET['tag']);
            $this->dataPath = dirname($debug->sSavePath);
        } else {
            //debug数据按日期来存放
            $this->dataPath = Yii::getAlias("@myerm/common/runtime/debug/".\Yii::$app->formatter->asDate(time()));
        }

        parent::bootstrap($app); // TODO: Change the autogenerated stub

        $this->logTarget = Yii::$app->getLog()->targets['debug'] = new LogTarget($this);
    }
}