<?php

namespace myerm\shop\common\controllers;

use myerm\common\controllers\MyERMController;

/**
 * 这是ShopERM的总控制器，所有ShopERM的控制器必须继承于它
 */
class ShopERMController extends MyERMController
{
    /**
     * @var Transaction $transaction 事务
     */
    public $transaction;

    public $events;

    public $sDevViewPath;

    public function beforeAction($action)
    {

        //开启会话
        \Yii::$app->frontsession->start();

        //注册事件处理器
        if ($this->events) {
            foreach ($this->events as $e) {
                $this->on($e[0], $e[1]);
            }
        }

        //跨域控制
//        header('Access-Control-Allow-Origin:*');
//        header('Access-Control-Allow-Methods:GET');

        return parent::beforeAction($action);
    }

    public function afterAction($action, $result)
    {
        //会话结束
        \Yii::$app->frontsession->end();

        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }
}