<?php

namespace myerm\backend\system\models;

/**
 * 系统对象模型-对象的操作权限项管理
 * ============================================================================
 * 版权所有 2010-2017 三只象（厦门）网络科技有限公司，并保留所有权利。
 * 网站地址: http://www.myerm.cn
 * ----------------------------------------------------------------------------
 * 这不是一个自由软件！您只能在不用于商业目的的前提下对程序代码进行修改和
 * 使用；不允许对程序代码以任何形式任何目的的再发布。
 * ============================================================================
 * @author 陈鹭明  <lumingchen@qq.com>
 * @since 2015-11-19 16:08
 * @version v2.0
 */
class SysObjectOperator extends \myerm\backend\system\models\Model
{
    public static function findOne($condition)
    {
        return \Yii::$app->cache->getOrSet(
            md5(serialize($condition)), function () use ($condition) {
            return parent::findOne($condition); // TODO: Change the autogenerated stub
        }
        );
    }

    public function getUsers()
    {
        $arrObjectID = [];
        $arr = SysOrgOperator::find()->select(['ObjectID'])->where("sObjectName='" . $this->sObjectName . "' AND sOperator='" . $this->sOperator . "' AND sOrgName='System/SysUser'")->all();
        foreach ($arr as $v) {
            $arrObjectID[] = $v->ObjectID;
        }

        if ($arrObjectID) {
            return SysUser::find()->select(['ID', 'sName'])->where("ID IN ('" . implode("','",
                    $arrObjectID) . "')")->asArray()->all();
        } else {
            return [];
        }
    }

    public function getDeps()
    {
        $arrObjectID = [];
        $arr = SysOrgOperator::find()->select(['ObjectID'])->where("sObjectName='" . $this->sObjectName . "' AND sOperator='" . $this->sOperator . "' AND sOrgName='System/SysDep'")->all();
        foreach ($arr as $v) {
            $arrObjectID[] = $v->ObjectID;
        }

        if ($arrObjectID) {
            return SysDep::find()->select(['ID', 'sName'])->where("ID IN ('" . implode("','",
                    $arrObjectID) . "')")->asArray()->all();
        } else {
            return [];
        }
    }

    public function getRoles()
    {
        $arrObjectID = [];
        $arr = SysOrgOperator::find()->select(['ObjectID'])->where("sObjectName='" . $this->sObjectName . "' AND sOperator='" . $this->sOperator . "' AND sOrgName='System/SysRole'")->all();
        foreach ($arr as $v) {
            $arrObjectID[] = $v->ObjectID;
        }

        if ($arrObjectID) {
            return SysRole::find()->select(['ID', 'sName'])->where("ID IN ('" . implode("','",
                    $arrObjectID) . "')")->asArray()->all();
        } else {
            return [];
        }
    }
}
